# Generated by Django 3.2 on 2021-04-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A 101 Transfurmations Customer', help_text='255 characters or less.', max_length=255, verbose_name='Customer Name')),
                ('comment', models.TextField(help_text='2000 characters or less.', max_length=2000, verbose_name='Comment')),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow, help_text='The date and time the review was created.', verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
